---
title: "Schedule"
---

1月28日現在の、メンター（敬称略）ごとの開催日候補です。実際の開催日は、メンターの方々に調整していただきます。

```{r, echo = FALSE}

rm(list=ls())  # reset workspace

# install & load packages
pacman::p_load(
  tidyverse
  , knitr  
  , kableExtra # nice tables
  , pander     # nice tables
)

# Rmarkdown settings
knitr::opts_chunk$set(
  prompt  = FALSE,  # Do not add > or + in inline-code
  message = FALSE, 
  comment = "", 
  warning = FALSE,  # Mute warnings
  tidy    = TRUE,
  echo = FALSE
  ) 
options(knitr.kable.NA = '') # Hide NAs in kable table

```

```{r, results='asis', echo = FALSE}

read_csv('./Schedule.csv') %>%
  ## Set sell text style for all dates and menters
  # To do so at once, gather cell for a column
  pivot_longer(cols = -1, names_to = "Menters", values_to = "Possibility") %>% 
  # Set cell style
  mutate(
    Possibility = text_spec(
      Possibility,
      bold = TRUE,
      font_size = 24,
      # Use color-blind friendly color sets
      color = ifelse(
        # Red for available
        Possibility == "○", rgb(1,0.157,0),
        ifelse(
          # Light-blue for unavailable
          Possibility == "△", rgb(1, 0.9608, 0), rgb(0.4, 0.8, 1)
          )))) %>%
  # Set each menter to column
  pivot_wider(names_from = Menters, values_from = Possibility) %>% 
  # Don't show cell styles as texts
  kable(escape = FALSE) %>%
  kable_styling(position = "left", full_width = FALSE) %>%
  # Column style
  column_spec(1, color = "black", background = "lightgrey", width = "20em") %>%
  # Row style
  row_spec(0, bold = FALSE, color = "black", background = "lightgrey") %>% 
  # Scrollable table
  scroll_box(width = "100%", height = "500px", fixed_thead = TRUE)
  
```

